### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'send')

### ISSUE THREAD

**Issue by crombieplex** [mjdean1994/sparkbot#3]
We are getting there, I appreciate you assisting with this. So I do have my channel id in the config, but getting this error now. 

root@localhost:~/sparkbot# node app.js
/root/sparkbot/lib/logger.js:9
    channel.send(`${prefixEmoji}\`${logMessage}\``)
            ^

TypeError: Cannot read properties of undefined (reading 'send')
    at send (/root/sparkbot/lib/logger.js:9:13)
    at Object.module.exports.info (/root/sparkbot/lib/logger.js:14:5)
    at Client.<anonymous> (/root/sparkbot/app.js:44:12)
    at Object.onceWrapper (node:events:646:26)
    at Client.emit (node:events:526:28)
    at WebSocketManager.triggerClientReady (/root/sparkbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:383:17)
    at WebSocketManager.checkShardsReady (/root/sparkbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:366:10)
    at WebSocketShard.<anonymous> (/root/sparkbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:188:14)
    at WebSocketShard.emit (node:events:526:28)
    at WebSocketShard.checkReady (/root/sparkbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:474:12)

Node.js v17.5.0

**Comment by mjdean1994** [comment]
It looks like in the code I'm grabbing the channel from the cache, which... I think should be fine here. For the channel you're using, is SparkBot in the Discord server and able to see the channel? The bot would show up on the right-hand side as one of the members of the channel.

Double check that for me, and if it's in there and can see it, I'll do some debugging on my end. Could be that grabbing the channel from the cache isn't the right thing to do.

**Comment by crombieplex** [comment]
So as soon as i type node app.js I get this error and the program exits. So the bot doesnt even show up in the server

**Comment by mjdean1994** [comment]
So you can invite a bot to the server regardless of if it’s online. Maybe I should add a blurb in the readme about that step. I’m not at my computer currently but there should be a way to generate an invite link for it from the Discord Developer Portal. Once it’s invited and granted the right perms to see the channel, try it again. If you can’t find the button I’m talking about I can look into it tomorrow and write up a step on the readme about it.

**Comment by crombieplex** [comment]
Ok! now we moving! But now it seems its not writing to the google sheet and basically each time I enter something I need to get a new auth code

[2/13/2022, 9:22:50 PM][info] Set flow state to "requestToken" for user 914311581645570088.
[2/13/2022, 9:23:23 PM][info] Handling direct message from user 914311581645570088...
[2/13/2022, 9:23:23 PM][info] Set flow state to "idle" for user 914311581645570088.
[2/13/2022, 9:23:30 PM][info] Handling button interaction from user 914311581645570088...
[2/13/2022, 9:23:33 PM][info] Handling button interaction from user 914311581645570088...
[2/13/2022, 9:23:33 PM][info] Set flow state to "companyEdit" for user 914311581645570088.
[2/13/2022, 9:23:47 PM][info] Handling direct message from user 914311581645570088...
[2/13/2022, 9:23:47 PM][info] Set attribute "company" to "The Iron Marble" for user 914311581645570088.
[2/13/2022, 9:23:47 PM][info] Set flow state to "idle" for user 914311581645570088.
[2/13/2022, 9:23:48 PM][error] Failed to update roster: Error: Unable to parse range: Roster!A:I
[2/13/2022, 9:23:48 PM][info] Getting a new token to talk to Google Sheets.
[2/13/2022, 9:23:48 PM][info] Set flow state to "requestToken" for user 914311581645570088.
[2/13/2022, 9:24:06 PM][info] Handling button interaction from user 914311581645570088...
[2/13/2022, 9:24:06 PM][info] Set flow state to "levelEdit" for user 914311581645570088.
[2/13/2022, 9:24:10 PM][info] Handling direct message from user 914311581645570088...
[2/13/2022, 9:24:10 PM][error] Failed to authorize to Google Sheets: "Cannot update as there's no token to use."
[2/13/2022, 9:24:10 PM][info] Getting a new token to talk to Google Sheets.
[2/13/2022, 9:24:10 PM][error] Failed to authorize to Google Sheets: "Expected a token but got an error: Error: ENOENT: no such file or directory, open './tokenCache.json'"
[2/13/2022, 9:24:10 PM][info] Set attribute "level" to "60" for user 914311581645570088.
[2/13/2022, 9:24:10 PM][info] Set flow state to "idle" for user 914311581645570088.
[2/13/2022, 9:24:10 PM][info] Set flow state to "requestToken" for user 914311581645570088.
[2/13/2022, 9:24:35 PM][info] Handling direct message from user 914311581645570088...
[2/13/2022, 9:24:35 PM][info] Set flow state to "idle" for user 914311581645570088.
[2/13/2022, 9:24:43 PM][info] Handling button interaction from user 914311581645570088...
[2/13/2022, 9:24:47 PM][info] Handling button interaction from user 914311581645570088...
[2/13/2022, 9:24:47 PM][info] Set flow state to "gearscoreEdit" for user 914311581645570088.
[2/13/2022, 9:24:50 PM][info] Handling direct message from user 914311581645570088...
[2/13/2022, 9:24:50 PM][info] Set attribute "gearscore" to "600" for user 914311581645570088.
[2/13/2022, 9:24:50 PM][info] Set flow state to "idle" for user 914311581645570088.
[2/13/2022, 9:24:50 PM][error] Failed to update roster: Error: Unable to parse range: Roster!A:I
[2/13/2022, 9:24:50 PM][info] Getting a new token to talk to Google Sheets.
[2/13/2022, 9:24:50 PM][info] Set flow state to "requestToken" for user 914311581645570088.

**Comment by crombieplex** [comment]
i think maybe the spreadsheet issue is when i click on the roster spreadsheet link it takes me to, https://docs.google.com/spreadsheets/d/1Uz2ltnnkQKmzMESLlV4FezepSCM1Lnk-w3Bs-KVj4eg/edit#gid=0

also when i click on Manage Wars there is no button to add a war, only go back

**Comment by mjdean1994** [comment]
Sounds like I must have hardcoded the roster link somewhere. Shame on me. I’ll fix that tomorrow. The “failed to parse range” error is probably because your spreadsheet tab isn’t named “Roster” like mine was. Maybe “spreadsheetTabName” should become a config option too. I will also implement that tomorrow.

**Comment by crombieplex** [comment]
no worries i copied that spreadsheet over to my account. 
I had to do a touch tokenCache.json and add the {} to it. 
And then the other issue with the verification link was the oAuth app was in the "testing" phase. Setting that to production has cleared those errors. 

Is there a certain role that needs to be created for the bot to give you create war access? Ive tried from 2 account now and neither of them can create a war

**Comment by mjdean1994** [comment]
Alright, I updated some stuff.
1. spreadsheetTabName is now a required config option. I updated the readme to explain that. That'll allow you to change it from "Roster" to whatever you want.
2. I added the need to create tokenCache.json to the README instructions. It looks like it's pretty simple to just create a file if it doesn't exist using the fs library that I'm already using in the project, but I decided not to bite that off right before bed. Maybe if I'm feeling ambitious tomorrow I'll do that refactoring.
3. I updated the roster link so that it doesn't always point to the one I was using back when I was running this bot. Instead it creates a link based on what's in config.json.

**Comment by crombieplex** [comment]
Awesome. I am still trying to figure out this grant function though. In the grantData.json file it doesn't show any roles, just 
{"USERID":{}}

and sending a message in dm to the bot with grant only returns the menu back to me

**Comment by mjdean1994** [comment]
Try adding “admin”: true inside of the curly braces for your user ID. I think that should work. I’ll update the readme for that.

**Comment by crombieplex** [comment]
ok, that added me as an admin and I get the grant button. I tried granting the role "war" but that still doesnt show the war buttons

**Comment by mjdean1994** [comment]
The name of the role for wars is "warCoordinator". Try that.

**Comment by crombieplex** [comment]
That worked. I am going to close this issue since we have gotten off topic on it. but will open a feature request
